### ISSUE TITLE
index timestamp ordering

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-backlinks#1]
I have realised that I actually need this index to be in asserted order timestamps (`msg.value.timestamp`) rather than receive order (`msg.timestamp`) for the channel pages.

It would double the size to have both indexes available (mine is 20 MB already). How do others feel about changing this index to be `msg.value.timestamp` instead? 

Or maybe doubling the index size isn't so bad?

@clehner @dominictarr @ahdinosaur @mixmix

**Comment by ahdinosaur** [comment]
happy if we doubled the index to have both timestamp orderings available, also happy if you prefer only the asserted order timestamp.

**Comment by mmckegg** [comment]
[Cel said this on ssb](https://viewer.scuttlebot.io/%25jtx5gOE1MlIZHz%2B62Gdl0TIB2XshhqOoznru5dSUhNU%3D.sha256):

> i'm okay with channels sorted by asserted timestamp. but i'm using ssb-backlinks for listing mentions also, and those i would want in received order. so i would suggest index by both

I think I'm just going to be adding another index!

**Comment by mmckegg** [comment]
Added the additional index in 92fbdafe376f4faa01b901b89e29eeb6927ade99
