### ISSUE TITLE
ssb-backlinks no longer works with scuttlebot@13.0.3

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-backlinks#11]
When I load the backlinks module I get this error and scuttlebot quits

```
/home/ev/mvd/node_modules/ssb-ref/index.js:109
    return /^(net|wss?|onion)$/.test(address[0].name) && /^shs/.test(address[1].name)
                                                                                ^

TypeError: Cannot read property 'name' of undefined
    at /home/ev/mvd/node_modules/ssb-ref/index.js:109:81
    at Array.find (<anonymous>)
    at /home/ev/mvd/node_modules/ssb-ref/index.js:108:15
    at /home/ev/mvd/node_modules/ssb-ref/index.js:99:15
    at parseMultiServerInvite (/home/ev/mvd/node_modules/ssb-ref/index.js:268:14)
    at exports.isMultiServerInvite (/home/ev/mvd/node_modules/ssb-ref/index.js:225:14)
    at exports.isInvite (/home/ev/mvd/node_modules/ssb-ref/index.js:231:36)
    at Object.exports.type (/home/ev/mvd/node_modules/ssb-ref/index.js:303:13)
    at /home/ev/mvd/node_modules/ssb-backlinks/emit-links.js:20:13
    at walk (/home/ev/mvd/node_modules/ssb-backlinks/emit-links.js:53:5)
```

**Comment by evbogue** [comment]
@mmckegg Are you also experiencing this error in Patchwork? I figure you're also using ssb-backlinks.

**Comment by mmckegg** [comment]
@evbogue I think patchwork is still on an older version of sbot. I did try running an `npm update` on patchwork earlier today and everything exploded horribly, so I reverted back to the package lock.

Sorry, I don't know if that's related to this issue.

**Comment by evbogue** [comment]
@mmckegg Yes, there's a lot going wrong right now throughout the entire scuttlebot stack.

**Comment by arj03** [comment]
That comment is not really super helpful @evbogue 

What version of ssb-ref are you using?

Looks like that bug was fixed here: https://github.com/ssbc/ssb-ref/commit/1bd2826eb2dc834a70c344a759671d8cf2c9c289

**Comment by evbogue** [comment]
@arj03 I was responding to @mmckegg's "exploded horribly" comment, with an affirmative. I apologize if that didn't come across quite right, but it is my experience that things are broken. 

I can however confirm that this is issue fixed and I'll close the issue.

Thank you @mixmix and @arj03 for taking the time to fix this issue!

**Comment by evbogue** [comment]
@arj03 I should also mention that I'm getting _way_ closer to everything being fixed in `mvd`. Gossip and `ws` are good to go, and now backlinks is up and running. 

I should be able to release a working version this weekend. :tada:
