### ISSUE TITLE
Documentation Drive Week 3

### ISSUE THREAD

**Issue by elevenpassin** [ssbc/ssb-backlinks#13]
#### Rate the current state of the documentation out of 10.
7

#### Is it clear what this is used for?

Yes

#### is there api documentation?
Yes & No. 

While documentation on basic usage is present with examples, API docs for all the properties / methods found in `index.js` is not present.

**Undocumented api list**
- exports.manifest
- exports.name
- exports.version
- exports.init

#### read code, do you see any undocumented methods?
Yes

#### for a method is there any undocumented options?
Yes

#### Additional comments:

It would be great if there was a link to a page that introduces plugins for scuttlebot (as in how to create new plugins / plug-in new plugins to sbot etc?)

**Comment by dominictarr** [comment]
linking to issue for needed plugins doc, so that we can fix this here when that is fixed: https://github.com/ssbc/secret-stack/issues/37
