### ISSUE TITLE
v0.7.x => v1.0.0 requires a rebuild of the indexes

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-backlinks#16]
The changes done from v0.7.x to v1.0.0, specifically, [this commit](https://github.com/ssbc/ssb-backlinks/commit/d637e763b69090b83f30d0f2e73f6c7f2e57b55c) were considered breaking changes and therefore the flumeview `indexVersion` was bumped from `8` to `9`. This means that the ssb-backlinks index will be destroyed and rebuilt. Depending on the end-user device and account, this may mean >=20min of rebuilding indexes.

What do you'all think if we reverted `indexVersion` from `9` to `8`, and released a new version `2.0.0`? This means that whoever is updating from `0.7.x` to `2.0.0` will stay on the same `indexVersion` and thus indexes won't be rebuilt. @arj03 told me that the `indexVersion` bump is semantic, and that's reasonable. On the other hand, do we know of anyone (any app) that depends on ssb-backlinks supporting invites and addresses? This could be one of those cases of "if it's not documented, it's not public API, so therefore changes are not considered breaking".

If releasing such `2.0.0` is too radical, another option is to make a branch and release a new version as `0.8.0` on some `npm dist-tag` that is not the `latest`.

**Comment by arj03** [comment]
I'm mostly for a 0.8.0 version

**Comment by staltz** [comment]
I ended up updating another indexVersion for another package, so I don't have a need for `0.8.0` anymore.
