### ISSUE TITLE
initialSync doesn't need unbox

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-backlinks#5]
on initial sync there are heaps of messages that are for sure not for me (my new keypair just came into existence)

how about we skip the unbox attempt for all messages published _before_ `(my first message timestamp | current time)`

considerations: 
- which timestamps should you trust?
- what if you haven't posted any message yet ?  (could be nice to know when a keypair was minted)

**Comment by mixmix** [comment]
mmm .. maybe wait till we have async unbox ... @pietgeursen 's rust unbox work could be really useful here

**Comment by arj03** [comment]
Interesting @mixmix. This is a good benchmark case. I'll add it to my list and do some investigations.

Related to what you want to skip I don't think there is any silver bullet. It will always be a tradeoff as you can never theoretically be sure what is ok to skip and what is not. But in practice, setting timestamp to 1 week before now seems resonable.

**Comment by mixmix** [comment]
Another idea would be a flumedb hook that unboxes messages before passing
them to all flumeViews. Right now there are at least 2 things trying
unboxes on every message ssb-private and ssb-backlinks.... And perhaps
ssb-chess too...

**Comment by arj03** [comment]
On my machine I have 27493 private messages out of 287670 total. Roughly 10%. The numbers are about the same if I look at the latest 30k.

**Comment by dominictarr** [comment]
question: how much difference does it make to time to rebuild indexes if you turn of unbox?

**Comment by mixmix** [comment]
A great question. does this fall in the domain of a benchmarking grant?
Is anyone really pumped by this ?

**Comment by arj03** [comment]
Indeed mix. I don't want to steal your thunder here, but I'm very pumped by this 😄 How can I help the best?

**Comment by mixmix** [comment]
I don't have capacity for this at the moment. If you want to drive in its
all yours!

**Comment by arj03** [comment]
Some ongoing investigations:

Reading through the whole log:

real	1m45.446s +/- 5 sec
user	0m53.645s +/- 1 sec

Reading through the whole log + unbox private messages:

real	1m44.718s +/- 10 sec
user	1m2.686s +/- 1 sec

(62-53) / 53 = ~17% extra user time.

**Comment by mixmix** [comment]
What's the real and user in this context?

**Comment by arj03** [comment]
Real is wall clock time, user is cpu time spent by the process. I'll add a benchmark to bench-ssb, just wanted to get some numbers out there.

**Comment by mixmix** [comment]
Thanks for the clarification

**Comment by arj03** [comment]
Added benchmarks to bench-ssb. My machine can decrypt / try to decrypt around 2100 messages per second.

**Comment by dominictarr** [comment]
I'm gonna propose private-groups for next month, which will take an overhaul of all this decryption in indexes stuff.

**Comment by dominictarr** [comment]
I'm gonna propose private-groups for next month, which will take an overhaul of all this decryption in indexes stuff.

**Comment by mixmix** [comment]
I take it back, we need decryption on first sync for resurrecting an
identity backup!
