### ISSUE TITLE
what's the `opts.index` ? 

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-backlinks#9]
I've read the source code here and in `flumeview-query/links`
looks like : 
- `opts.index` slaps `{ $sort: opt.index }` on the end of your MFR query
- in `flumeview-query/links` this is popped off, and is used to try and find a matching index you're telling it to use.

here's the bit that don't make sense to me - the way it looks for an index is this method : https://github.com/flumedb/flumeview-query/blob/18427ccc16627e641bdd6bed350eca4d5cb9363d/util.js#L35-L39

which looks for a match on the `value` of an index description .. .not the `key`... so the example in the README just looks like it should break, but I don't think it does.

finally in the code there's a comment which says "this is for backwards compatability"
What is this hocus pocus ?
Did I miss something?

# :crying_cat_face:

**Comment by mixmix** [comment]
If it's legacy and not needed, lets dump it from the README ? :red_circle: :fish:

**Comment by mmckegg** [comment]
@mixmix 

It's definitely needed. It is defined here: https://github.com/ssbc/ssb-backlinks/blob/f53d300b9b88bb39780a714b91a9c2682fceec69/index.js#L29-L37

But yeah, it is kind of legacy. After the ssb-query fork was removed, @dominictarr added a way to choose the index order. But I preferred the old API for backlinks so a wrote shim.

You could document the new way instead though:

```js
  var filterQuery = {
    $filter: {
      dest: id
    }
  }

  return sbot.backlinks.read({
    query: [filterQuery, {$sort: [['dest'], ['rts']]}],
    live: true
  })
```

The issue I have with that is you have to type the index exactly as it appears in the code otherwise it won't use the cache and will just buffer the entire db 😨

**Comment by mixmix** [comment]
yeah but if you don't have sort, it rolls on to `read(opts)`

which leads you here : 
> https://github.com/flumedb/flumeview-query/blob/master/links.js#L68-L70
(how the shit did you drop in that codeblock)


which then determines the index for you D:
So I _think_ you're mistaken?

**Comment by mmckegg** [comment]
The problem is that sometimes queries are ambiguous. There might be more than one (or _no_ for that matter) indexes that can resolve your query, but their results might be in a different order and that might be important.

Okay, I have no idea how I inserted the code block. GitHub is weird.

**Comment by mmckegg** [comment]
I think a far better API for this particular case is an option that you pass to `ssb.backlinks.read`, saying whether to use asserted timestamps or not. 

`ssb.backlinks.read({useAssertedTimestamps: true})` and then just be done with it 😆

**Comment by mixmix** [comment]
oh yeah, I'd be up for that sort of thing ... I notice I've just internalised adding a `{$gt: 0}` entry in the right place to trigger the right index ... 

there's also this annoying thing where if you say `{ author: { $ne: @mix } }` it goes "oh hey, looks like I should use an author-based index" and then totally shits itself. End up having to write a query like `[ { $filter }, { $filter } ]` and put the not-this-author index in the second filter....

**Comment by mmckegg** [comment]
Yeah, those sorts of issues are exactly why I added the index chooser hack. But it really violates the entire point of even having `flumeview-query`. Maybe it would be better with a more explicit, simpler API, without query. I  basically never use any other query than specifying which index to use 😆

**Comment by mixmix** [comment]
But the other important perk is server side filtering to reduce amount
transferred
